version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-app-tomcat
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: sicefa
      MYSQL_USER: sicefa
      MYSQL_PASSWORD: sicefa
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sicefa
      MYSQL_USER: sicefa
      MYSQL_PASSWORD: sicefa
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/


volumes:
  db_data:
